---
- name: Deploy a jar file
  hosts: ubuntu18
  remote_user: himank
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/calculatorDevOps-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/
        
    - name: set the stable repository
      apt_repository: 
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        
    - name: Install docker.
      package:
        name: docker-ce
        state: present
      
    - name: Start docker service
      service:
        name: docker
        state: started
      
    - name: pull an image
      docker_image:
        name: himankjn/check
