---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: himankjn/check
        source: pull
    - name: Create a data container
      docker_container:
        name: container1
        image: himankjn/check
    - name: deploy docker container
      docker_container:
        image: himankjn/check
        name: container2
        state: started
        auto_remove: true
        ports:
          - "8080:80"
